server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: all
  static_configs:
  - targets:
      - localhost
    labels:
      job: containerlogs
      __path__: /var/lib/docker/containers/*/*log
- job_name: docker
  # use docker.sock to filter containers
  docker_sd_configs:
    - host: "unix:///var/run/docker.sock"
      refresh_interval: 15s
      filters:
        - name: label
          values: ["com.docker.compose.project=corrid"]
  # use container name to create a loki label
  relabel_configs:
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container'

    # not allowed characters ('.', '-') in label names are replaced with underscores
    # https://github.com/prometheus/docs/issues/735
    - source_labels: ['__meta_docker_container_label_cz_cs_soft_service_kind']
      regex: '(.*)'
      target_label: 'kind'